server:
  port: 80
  
flowable:
#关闭定时任务JOB
  async-executor-activate: false
  # 自动生成flowable相关表 第一次生成后建议关闭提高运行速度
  database-schema-update: false
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowable_spring_boot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: admin
  